apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather_app
  labels:
    app: weather_app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather_app
  template:
    metadata:
      labels:
        app: weather_app
    spec:
      containers:
        - name: weather_app
          image: satyam1603/weather_app:latest  # <-- Replace with your Docker image
          ports:
            - containerPort: 80

